/// The entrypoint for the **server** environment, which for a static build is
/// the only one that renders anything: `jaspr build` runs this once and writes
/// the result to `build/jaspr/index.html`.
library;

import 'package:jaspr/server.dart';

import 'landing/landing_page.dart';
import 'seo.dart';

// Generated by jaspr_builder — do not edit.
import 'main.server.options.dart';

const String _description =
    'litetune fine-tunes a small language model, converts it into a .litertlm '
    'file that runs on a phone through LiteRT-LM, and measures what the '
    'conversion cost on your own task before you ship it.';

const String _title = 'litetune — fine-tune, convert, and check what it cost';

void main() {
  Jaspr.initializeApp(options: defaultServerOptions);

  runApp(
    Document(
      title: _title,
      lang: 'en',
      meta: const {'description': _description},
      head: [
        ...fontLinks(),
        ...seoHead(title: _title, description: _description),
      ],
      body: const LandingPage(),
    ),
  );
}
