/// The entrypoint for the **client** environment.
///
/// The page carries no interactive components, so this only mounts the (empty)
/// client app. It stays because Jaspr's build expects both entrypoints, and
/// because the first `@client` component added later needs no wiring beyond
/// its own annotation.
library;

import 'package:jaspr/client.dart';

// Generated by jaspr_builder — do not edit.
import 'main.client.options.dart';

void main() {
  Jaspr.initializeApp(options: defaultClientOptions);
  runApp(const ClientApp());
}
