/// The entrypoint for the **server** environment, which for a static build is
/// the only one that renders anything: `jaspr build` runs this once and writes
/// one HTML file per route -- `build/jaspr/index.html`,
/// `build/jaspr/changelog/index.html` and
/// `build/jaspr/measurements/index.html`.
library;

import 'package:jaspr/server.dart';
import 'package:jaspr_router/jaspr_router.dart';

import 'changelog/changelog_page.dart';
import 'landing/landing_page.dart';
import 'measurements/measurements_page.dart';
import 'project.dart';
import 'seo.dart';

// Generated by jaspr_builder — do not edit.
import 'main.server.options.dart';

const String _description =
    'litetune fine-tunes a small language model, converts it into a .litertlm '
    'file that runs on a phone through LiteRT-LM, and measures what the '
    'conversion cost on your own task before you ship it.';

const String _title = 'litetune — fine-tune, convert, and check what it cost';

const String _changelogDescription =
    'Every litetune release, newest first. A release that makes an earlier '
    'result wrong says so first, and says what to do about it.';

const String _changelogTitle = 'Changelog — litetune';

const String _measurementsDescription =
    'Every number litetune has measured, with the interval, the sample size '
    'and the refusals beside it -- and what each run does not establish.';

const String _measurementsTitle = 'Measurements — litetune';

void main() {
  Jaspr.initializeApp(options: defaultServerOptions);

  // `jaspr_router` in static mode renders every route it is given, which is
  // how the build knows `/changelog` exists: nothing links the two pages at
  // build time, and a route missing here is a page missing from the deploy.
  runApp(
    Router(
      routes: [
        Route(
          path: '/',
          builder: (context, state) => Document(
            title: _title,
            lang: 'en',
            meta: const {'description': _description},
            head: [
              ...fontLinks(),
              ...seoHead(title: _title, description: _description),
            ],
            body: LandingPage(version: packageVersion),
          ),
        ),
        Route(
          path: '/changelog',
          builder: (context, state) => Document(
            title: _changelogTitle,
            lang: 'en',
            meta: const {'description': _changelogDescription},
            head: [
              ...fontLinks(),
              ...seoHead(
                title: _changelogTitle,
                description: _changelogDescription,
                applicationDescription: _description,
                path: '/changelog',
              ),
            ],
            body: ChangelogPage(
              version: packageVersion,
              markdown: changelogMarkdown,
            ),
          ),
        ),
        Route(
          path: '/measurements',
          builder: (context, state) => Document(
            title: _measurementsTitle,
            lang: 'en',
            meta: const {'description': _measurementsDescription},
            head: [
              ...fontLinks(),
              ...seoHead(
                title: _measurementsTitle,
                description: _measurementsDescription,
                applicationDescription: _description,
                path: '/measurements',
              ),
            ],
            body: MeasurementsPage(
              version: packageVersion,
              markdown: measurementsMarkdown,
            ),
          ),
        ),
      ],
    ),
  );
}
